//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameStoreEntities : DbContext
    {
        public GameStoreEntities()
            : base("name=GameStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SanPham>()
        .HasMany(sp => sp.HinhAnh) // SanPham có nhiều HinhAnh
        .WithRequired(ha => ha.SanPham) // HinhAnh yêu cầu SanPham
        .HasForeignKey(ha => ha.maSP);
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs{ get; set; }
        public virtual DbSet<ChiTietGioHang> ChiTietGioHangs{ get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<GioHang> GioHangs { get; set; }
        public virtual DbSet<HinhAnh> HinhAnhs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens{ get; set; }
        public virtual DbSet<SanPham> SanPhams{ get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
